require("dotenv").config();
const Game = require("./models/Game");
const Player = require("./models/Player");
const Team = require("./models/Team");
const Statistic = require("./models/Statistic");
const sequelize = require("./db/config");


sequelize
  .sync()
  .then(() => {


Player.bulkCreate([
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Sophmore",
  },
  {
    full_name: null,
    class: "Sophmore",
  },
  {
    full_name: null,
    class: "Sophmore",
  },
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Sophmore",
  },
  {
    full_name: null,
    class: "Junior",
  },
  {
    full_name: null,
    class: "Sophmore",
  },
]);

Team.create({
  school_name: "Atlanta",
  school_mascot: "Tigers",
  coach: null,
});

Game.bulkCreate([
  {
    game_date: "02/17",
    location: "Chapel Hill",
  },
  {
    game_date: "02/23",
    location: "Lithia Springs",
  },
  {
    game_date: "03/03",
    location: "Mt. Zion",
  },
  {
    game_date: "03-08",
    location: "Pebblebrook",
  },
  {
    game_date: "03/09",
    location: "Meadowcreek",
  },
  {
    game_date: "03/11",
    location: "Hamilton",
  },
  {
    game_date: "03/15",
    location: "Dalton",
  },
  {
    game_date: "03/17",
    location: "St. Marks",
  },
  {
    game_date: "03/18",
    location: "Carrollton",
  },
  {
    game_date: "03/22",
    location: "Ridgeway",
  },
]);

Statistic.bulkCreate([
  {
    battling_average: 0.0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.25,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 1,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 4,
    at_bats: 3,
    runs: 2,
    hits: 1,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 2,
    runs: 3,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 2,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 1,
    runs_batted_in: 2,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.0,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 3,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.25,
    plate_appearances: 4,
    at_bats: 4,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 4,
    at_bats: 3,
    runs: 2,
    hits: 1,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 1,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 0,
    at_bats: 0,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 1,
    at_bats: 0,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 1,
    at_bats: 1,
    runs: 3,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 0,
    at_bats: 0,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 0,
    at_bats: 0,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 0,
    at_bats: 0,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 0,
    at_bats: 0,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 1,
    runs: 3,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 4,
    at_bats: 0,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 4,
    at_bats: 3,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 2,
    runs: 2,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 2,
    runs: 3,
    hits: 1,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.75,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 3,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 3,
    runs_batted_in: 3,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 5,
    at_bats: 3,
    runs: 0,
    hits: 3,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.667,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 2,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 2,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 1,
    runs: 2,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 1,
    runs: 1,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 2,
    at_bats: 0,
    runs: 0,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 5,
    at_bats: 2,
    runs: 2,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.6,
    plate_appearances: 5,
    at_bats: 5,
    runs: 1,
    hits: 3,
    runs_batted_in: 2,
    doubles: 3,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 1,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 1,
    at_bats: 1,
    runs: 1,
    hits: 1,
    runs_batted_in: 1,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 2,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 1,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 4,
    at_bats: 4,
    runs: 2,
    hits: 4,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 1,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 3,
    at_bats: 1,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 4,
    runs: 2,
    hits: 2,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 2,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    plate_appearances: 1,
    at_bats: 0,
    runs: 1,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 2,
    at_bats: 2,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 3,
    at_bats: 2,
    runs: 2,
    hits: 2,
    runs_batted_in: 1,
    doubles: 0,
    triples: 1,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.667,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 2,
    runs_batted_in: 1,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 3,
    at_bats: 2,
    runs: 1,
    hits: 1,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 4,
    at_bats: 3,
    runs: 1,
    hits: 1,
    runs_batted_in: 2,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 3,
    runs: 1,
    hits: 0,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 1,
    runs: 1,
    hits: 0,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 1,
    runs: 2,
    hits: 0,
    runs_batted_in: 3,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.75,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 3,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.667,
    plate_appearances: 3,
    at_bats: 3,
    runs: 0,
    hits: 2,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 2,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 1,
    at_bats: 1,
    runs: 1,
    hits: 1,
    runs_batted_in: 1,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 3,
    at_bats: 2,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 4,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.333,
    plate_appearances: 5,
    at_bats: 3,
    runs: 0,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 1,
    plate_appearances: 4,
    at_bats: 4,
    runs: 3,
    hits: 4,
    runs_batted_in: 4,
    doubles: 1,
    triples: 0,
    home_runs: 1,
  },
  {
    battling_average: 0.25,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.25,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 1,
    runs_batted_in: 0,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.75,
    plate_appearances: 4,
    at_bats: 4,
    runs: 1,
    hits: 3,
    runs_batted_in: 2,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.6,
    plate_appearances: 5,
    at_bats: 5,
    runs: 2,
    hits: 3,
    runs_batted_in: 2,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 4,
    runs: 2,
    hits: 2,
    runs_batted_in: 1,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 5,
    at_bats: 4,
    runs: 0,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0,
    plate_appearances: 4,
    at_bats: 3,
    runs: 1,
    hits: 0,
    runs_batted_in: 0,
    doubles: 0,
    triples: 0,
    home_runs: 0,
  },
  {
    battling_average: 0.5,
    plate_appearances: 4,
    at_bats: 2,
    runs: 2,
    hits: 1,
    runs_batted_in: 0,
    doubles: 1,
    triples: 0,
    home_runs: 0,
  },
]);


    return Player.findAll();
  })
  .then((players) => {
      players.forEach((player) => {
        player.setTeam(1);
        player.addStatistic((player.id * 10) - 1);
        player.addStatistic((player.id * 10) - 2);
        player.addStatistic((player.id * 10) - 3);
        player.addStatistic((player.id * 10) - 4);
        player.addStatistic((player.id * 10) - 5);
        player.addStatistic((player.id * 10) - 6);
        player.addStatistic((player.id * 10) - 7);
        player.addStatistic((player.id * 10) - 8);
        player.addStatistic((player.id * 10) - 9);
        player.addStatistic((player.id * 10));
      })

    })
  .catch((err) => {
    console.log(err);
  });
